# Generated by Django 5.1.4 on 2025-01-04 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bagage',
            fields=[
                ('id_bagage', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=128)),
                ('poids_total', models.IntegerField()),
                ('frais_bagage', models.DecimalField(decimal_places=2, max_digits=13)),
                ('type_bagage', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Bateau',
            fields=[
                ('no_bateau', models.AutoField(primary_key=True, serialize=False)),
                ('nom_bateau', models.CharField(max_length=128)),
                ('capacite_bateau', models.CharField(max_length=128)),
                ('type_bateau', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('no_client', models.AutoField(primary_key=True, serialize=False)),
                ('nom_client', models.CharField(max_length=128)),
                ('prenom_client', models.CharField(blank=True, max_length=128, null=True)),
                ('num_client', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employeur',
            fields=[
                ('id_emp', models.AutoField(primary_key=True, serialize=False)),
                ('nom_emp', models.CharField(max_length=128)),
                ('prenom_emp', models.CharField(blank=True, max_length=128, null=True)),
                ('poste_emp', models.CharField(max_length=128)),
                ('adresse_emp', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Passager',
            fields=[
                ('no_passager', models.AutoField(primary_key=True, serialize=False)),
                ('nom_passager', models.CharField(max_length=128)),
                ('prenom_passager', models.CharField(blank=True, max_length=128, null=True)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('code_port', models.AutoField(primary_key=True, serialize=False)),
                ('ville', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Billet',
            fields=[
                ('no_billet', models.AutoField(primary_key=True, serialize=False)),
                ('date_paiement', models.DateTimeField()),
                ('montants', models.DecimalField(decimal_places=2, max_digits=13)),
                ('mode_paiement', models.CharField(max_length=128)),
                ('no_passager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.passager')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id_res', models.AutoField(primary_key=True, serialize=False)),
                ('date_res', models.DateTimeField()),
                ('tarif_res', models.DecimalField(decimal_places=2, max_digits=13)),
                ('quantite_res', models.IntegerField()),
                ('no_billet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.billet')),
                ('no_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.client')),
            ],
        ),
        migrations.AddField(
            model_name='passager',
            name='id_res',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.reservation'),
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('no_transport', models.AutoField(primary_key=True, serialize=False)),
                ('datedepart', models.DateTimeField()),
                ('datearrive', models.DateTimeField()),
                ('code_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages_arrivee', to='produits.port')),
                ('code_port_quitte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages_depart', to='produits.port')),
            ],
        ),
        migrations.CreateModel(
            name='Responsabilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_responsabilite', models.CharField(max_length=128)),
                ('id_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.employeur')),
                ('no_transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.voyage')),
            ],
            options={
                'unique_together': {('id_emp', 'no_transport')},
            },
        ),
        migrations.CreateModel(
            name='Enregistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bagage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.bagage')),
                ('no_passager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.passager')),
                ('no_transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.voyage')),
            ],
            options={
                'unique_together': {('no_passager', 'id_bagage', 'no_transport')},
            },
        ),
        migrations.CreateModel(
            name='Effectue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_bateau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.bateau')),
                ('no_transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.voyage')),
            ],
            options={
                'unique_together': {('no_bateau', 'no_transport')},
            },
        ),
    ]
